"""PRD writer agent (port 8006).

Takes the requirement set and writes the narrative around it: summary, problem
statement, goals, non-goals, personas, user stories, metrics, risks, milestones.

The requirement *table* is not regenerated by the model - it is passed through
verbatim from the analyst. The writer only produces prose and the structures
that reference requirements by id. That separation is what keeps the traceability
matrix trustworthy: the writer cannot quietly reword a requirement or drop a
citation while "improving the flow".
"""

from __future__ import annotations

import logging
import re
from typing import Any

from pydantic import BaseModel, Field

from sourcework.a2a_common import Progress, SkillError, SkillExecutor, build_card, public_url, skill
from sourcework.agents.prompts import load
from sourcework.agents.schemas import WriteRequest, WriteResult
from sourcework.confluence.storage import render_prd
from sourcework.llm import LLM, register_stub
from sourcework.models import (
    Metric,
    Milestone,
    PRDDocument,
    PRDSection,
    Risk,
    UserStory,
)
from sourcework.render import to_markdown

logger = logging.getLogger(__name__)

PORT = 8006

MAX_PROMPT_EVIDENCE = 200
"""Evidence items put in front of the writer. Beyond this the prompt would grow
without bound; the cap is reported rather than applied in silence, because a
narrative written against a shortened evidence set is a different document."""

TEMPLATES = {
    "standard": load("writer_template_standard"),
    "lean": load("writer_template_lean"),
    "technical": load("writer_template_technical"),
    "discovery": load("writer_template_discovery"),
}

SYSTEM = load("writer_system")


class NarrativeDraft(BaseModel):
    summary: str = Field(description="3-5 sentences a busy exec could read alone.")
    problem_statement: str = ""
    background: str = ""
    goals: list[str] = Field(default_factory=list)
    non_goals: list[str] = Field(default_factory=list)
    personas: list[str] = Field(default_factory=list)
    user_stories: list[UserStory] = Field(default_factory=list)
    metrics: list[Metric] = Field(default_factory=list)
    risks: list[Risk] = Field(default_factory=list)
    milestones: list[Milestone] = Field(default_factory=list)
    extra_sections: list[PRDSection] = Field(default_factory=list)


class WriterExecutor(SkillExecutor):
    def __init__(self) -> None:
        self.llm = LLM(role="reasoning")
        self.skills = {
            "write_prd": self.write_prd,
            "render_prd": self.render_only,
        }
        self.default_skill = "write_prd"
        super().__init__()

    async def write_prd(self, payload: dict[str, Any], progress: Progress) -> WriteResult:
        req = WriteRequest.model_validate(payload)
        if not req.requirement_set.requirements:
            raise SkillError("The requirement set is empty; there is nothing to write about.")

        template = TEMPLATES.get(req.template, TEMPLATES["standard"])
        await progress(
            f"Drafting '{req.title}' ({req.template} template, "
            f"{len(req.requirement_set.requirements)} requirements)"
        )

        system = SYSTEM
        system += "\n\n" + load("writer_frame", template=template, audience=req.audience)
        if req.instructions:
            system += "\n\n" + load("writer_instruction", instructions=req.instructions)
        if req.revision_notes:
            system += "\n\n" + load(
                "writer_revision",
                notes="\n".join(f"- {n}" for n in req.revision_notes),
            )

        if len(req.evidence) > MAX_PROMPT_EVIDENCE:
            await progress(
                f"{len(req.evidence) - MAX_PROMPT_EVIDENCE} evidence item(s) left out of the "
                f"writer prompt (showing {MAX_PROMPT_EVIDENCE}); the PRD still cites the full set"
            )
        draft = await self.llm.structured(
            system, _context(req), NarrativeDraft, role="reasoning"
        )
        await progress("Assembling document and validating requirement references")

        valid_ids = {r.id for r in req.requirement_set.requirements}
        prd = PRDDocument(
            title=req.title,
            summary=draft.summary,
            problem_statement=draft.problem_statement,
            background=draft.background,
            goals=draft.goals,
            non_goals=draft.non_goals,
            personas=draft.personas,
            user_stories=[
                s.model_copy(
                    update={"requirement_ids": [i for i in s.requirement_ids if i in valid_ids]}
                )
                for s in draft.user_stories
            ],
            requirements=req.requirement_set,
            metrics=draft.metrics,
            risks=draft.risks,
            milestones=[
                m.model_copy(
                    update={"requirement_ids": [i for i in m.requirement_ids if i in valid_ids]}
                )
                for m in draft.milestones
            ],
            extra_sections=draft.extra_sections,
            sources=req.sources,
            evidence=req.evidence,
        )

        markdown = to_markdown(prd)
        storage = render_prd(prd)
        uncovered = valid_ids - {
            i for m in prd.milestones for i in m.requirement_ids
        } if prd.milestones else set()
        if uncovered:
            logger.info("%d requirement(s) not assigned to a milestone", len(uncovered))

        return WriteResult(
            prd=prd,
            markdown=markdown,
            confluence_storage=storage,
            summary=f"Drafted '{req.title}': {len(valid_ids)} requirements, "
            f"{len(prd.user_stories)} user stories, {len(prd.risks)} risks.",
        )

    async def render_only(self, payload: dict[str, Any]) -> WriteResult:
        """Re-render an existing PRD without invoking a model."""
        prd = PRDDocument.model_validate(payload.get("prd", payload))
        return WriteResult(
            prd=prd,
            markdown=to_markdown(prd),
            confluence_storage=render_prd(prd),
            summary=f"Re-rendered '{prd.title}'.",
        )


def _context(req: WriteRequest) -> str:
    rs = req.requirement_set
    lines = [f"Product: {req.title}", "", "REQUIREMENTS (verbatim, do not restate):"]
    for r in rs.requirements:
        lines.append(
            f"- {r.id} [{r.priority.value}/{r.kind.value}"
            f"{'/derived' if r.derived else ''}] {r.title}: {r.statement}"
        )
    if rs.conflicts:
        lines += ["", "UNRESOLVED CONFLICTS:"]
        lines += [f"- {' vs '.join(c.requirement_ids)}: {c.description}" for c in rs.conflicts]
    if rs.open_questions:
        lines += ["", "OPEN QUESTIONS:"]
        lines += [
            f"- {'[blocking] ' if q.blocking else ''}{q.question}" for q in rs.open_questions
        ]
    if rs.glossary:
        lines += ["", "GLOSSARY:"] + [f"- {k}: {v}" for k, v in rs.glossary.items()]
    lines += ["", "SOURCES:"]
    lines += [f"- {s.title} ({s.modality.value})" for s in req.sources]
    lines += ["", "SUPPORTING EVIDENCE (for grounding the narrative only):"]
    for e in req.evidence[:MAX_PROMPT_EVIDENCE]:
        lines.append(f"- [{e.kind}] {e.text}")
    return "\n".join(lines)


def card():  # noqa: ANN201
    return build_card(
        name="PRD Writer",
        description=(
            "Writes the PRD narrative around a fixed requirement set and renders it to "
            "Markdown and Confluence storage format. Never rewrites requirements."
        ),
        url=public_url(PORT),
        skills=[
            skill(
                "write_prd",
                "Write a PRD",
                "Produce a full PRD from a requirement set: narrative, user stories, "
                "metrics, risks and milestones, plus Markdown and Confluence renderings.",
                tags=["prd", "writing"],
            ),
            skill(
                "render_prd",
                "Re-render a PRD",
                "Deterministically re-render an existing PRD document to Markdown and "
                "Confluence storage format. No model call.",
                tags=["prd", "rendering"],
            ),
        ],
    )


def executor() -> SkillExecutor:
    return WriterExecutor()


# -- stub mode --------------------------------------------------------------


def _stub_narrative(user: str) -> dict[str, Any]:
    ids = re.findall(r"^- (REQ-\d+)", user, re.MULTILINE)
    return {
        "summary": "[stub] Narrative generated without a model. Not a real PRD.",
        "problem_statement": "[stub] Problem statement placeholder.",
        "goals": ["[stub] goal"],
        "non_goals": ["[stub] non-goal"],
        "personas": ["[stub] persona"],
        "user_stories": [
            {
                "id": "US-001",
                "persona": "stub user",
                "want": "the pipeline to run without credentials",
                "so_that": "the wiring can be tested",
                "requirement_ids": ids[:3],
            }
        ],
        "metrics": [{"name": "[stub] metric", "definition": "placeholder"}],
        "risks": [{"description": "[stub] risk", "mitigation": "configure a real model"}],
        "milestones": [{"name": "M1", "description": "[stub]", "requirement_ids": ids}],
    }


register_stub("NarrativeDraft", _stub_narrative)
